In [195]:
import numpy as np
import pandas as pd

In [196]:
true_news = pd.read_csv(r"C:\Users\ADMIN\DS\Vasanth\Vasanth\Dataset\True.csv")
fake_news = pd.read_csv(r"C:\Users\ADMIN\DS\Vasanth\Vasanth\Dataset\Fake.csv")

In [197]:
true_news

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [198]:
fake_news

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [199]:
true_df=pd.concat([true_news['title'],pd.Series(0,index=true_news.index, name='label')],axis=1)
fake_df=pd.concat([fake_news['title'],pd.Series(1,index=fake_news.index, name='label')],axis=1)

In [200]:
true_df

                                                   title  label
0      As U.S. budget fight looms, Republicans flip t...      0
1      U.S. military to accept transgender recruits o...      0
2      Senior U.S. Republican senator: 'Let Mr. Muell...      0
3      FBI Russia probe helped by Australian diplomat...      0
4      Trump wants Postal Service to charge 'much mor...      0
...                                                  ...    ...
21412  'Fully committed' NATO backs new U.S. approach...      0
21413  LexisNexis withdrew two products from Chinese ...      0
21414  Minsk cultural hub becomes haven from authorities      0
21415  Vatican upbeat on possibility of Pope Francis ...      0
21416  Indonesia to buy $1.14 billion worth of Russia...      0

[21417 rows x 2 columns]

In [201]:
fake_df

                                                   title  label
0       Donald Trump Sends Out Embarrassing New Year’...      1
1       Drunk Bragging Trump Staffer Started Russian ...      1
2       Sheriff David Clarke Becomes An Internet Joke...      1
3       Trump Is So Obsessed He Even Has Obama’s Name...      1
4       Pope Francis Just Called Out Donald Trump Dur...      1
...                                                  ...    ...
23476  McPain: John McCain Furious That Iran Treated ...      1
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...      1
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...      1
23479  How to Blow $700 Million: Al Jazeera America F...      1
23480  10 U.S. Navy Sailors Held by Iranian Military ...      1

[23481 rows x 2 columns]

In [202]:
news_df=pd.concat([true_df,fake_df], axis=0).sample(frac=1.0, random_state=34).reset_index(drop=True)

In [203]:
news_df

                                                   title  label
0        SUNDAY SCREENING: ‘The War on Democracy’ (2007)      1
1      SAY WHAT? Obama Gives Go Ahead For New UN “Reg...      1
2      U.S. farm groups oppose Trump's cuts to agricu...      0
3      BREAKING: Federal Judge STOPS Obamacare Transg...      1
4      OBAMA NOMINATES FIRST MUSLIM FOR FEDERAL BENCH...      1
...                                                  ...    ...
44893   Laura Bush Stuns Republican Party – Hinted Th...      1
44894   Here’s How Much Trump Is Paying Omarosa, Kell...      1
44895  REALLY FAKE NEWS: New York Times Finally Retra...      1
44896  WHOA! SENATOR TOM COTTON Blasts Harry Reid’s “...      1
44897   UK's May to visit China around Jan. 31: Sky News      0

[44898 rows x 2 columns]

In [204]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer 
stop_words=stopwords.words('english')
 
TEXT_CLEANING_RE = "@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+"

In [205]:
def preprocess(title, stem=False):
    # Remove link,user and special characters
    title = re.sub(TEXT_CLEANING_RE, ' ', str(title).lower()).strip()
    tokens = []
    for token in title.split():
        if token not in stop_words:
            if stem:
                tokens.append(stemmer.stem(token))
            else:
                tokens.append(token)
    return " ".join(tokens)
news_df['title'] = news_df['title'].apply(lambda x: preprocess(x))

In [206]:
news_df['title']

0                      sunday screening war democracy 2007
1        say obama gives go ahead new un regional hub w...
2        u farm groups oppose trump cuts agriculture sp...
3        breaking federal judge stops obamacare transge...
4        obama nominates first muslim federal bench dev...
                               ...
44893    laura bush stuns republican party hinted plans...
44894    much trump paying omarosa kellyanne conway sea...
44895    really fake news new york times finally retrac...
44896    whoa senator tom cotton blasts harry reid canc...
44897            uk may visit china around jan 31 sky news
Name: title, Length: 44898, dtype: object

In [207]:
from nltk.tokenize import RegexpTokenizer
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = TfidfVectorizer(stop_words='english',ngram_range = (1,3),tokenizer = token.tokenize)
test_counts= cv.fit_transform(news_df['title'])

C:\Users\ADMIN\anaconda3\New folder\lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [208]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(test_counts, news_df['label'],test_size=0.25,random_state=5)

# LogisticRegression

In [209]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [210]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, y_pred) 
print(f"Test accuracy: {accuracy:.4f}")

Test accuracy: 0.9371

In [211]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)
print(cm)

[[4998  327]
 [ 379 5521]]

In [212]:
from sklearn.metrics import roc_auc_score
acc = roc_auc_score(Y_test, y_pred)
print("Test set auc: {:.4f}".format(acc))

Test set auc: 0.9372